// Auto-generated by Update Season Library.ps1 from ./season-images/.
window.PAINT_LAB_SEASON_LIBRARY = {
  season: 'season-2026',
  version: '2026-07-26-milestone-1',
  images: [
    { name: 'All My Love.png', url: 'season-images/All%20My%20Love.png' },
    { name: 'Arctic Chill.png', url: 'season-images/Arctic%20Chill.png' },
    { name: 'Fall Leaves.png', url: 'season-images/Fall%20Leaves.png' },
    { name: 'Floral.png', url: 'season-images/Floral.png' },
    { name: 'Get Lucky 2.png', url: 'season-images/Get%20Lucky%202.png' },
    { name: 'Get Lucky.png', url: 'season-images/Get%20Lucky.png' },
    { name: 'In The Clouds.png', url: 'season-images/In%20The%20Clouds.png' },
    { name: 'Splash.png', url: 'season-images/Splash.png' },
    { name: 'Spooky Night 2.png', url: 'season-images/Spooky%20Night%202.png' },
    { name: 'Spooky Night.png', url: 'season-images/Spooky%20Night.png' },
    { name: 'themobilepaintlablogoBandW.png', url: 'season-images/themobilepaintlablogoBandW.png' }
  ]
};
