// Auto-generated by Update Season Library.ps1 from ./season-images/.
window.PAINT_LAB_SEASON_LIBRARY = {
  season: 'spring-2026',
  version: '2026-04-08',
  images: [
    { name: 'themobilepaintlablogoBandW.png', url: 'season-images/themobilepaintlablogoBandW.png' }
  ]
};
