param(
  [string]$Season,
  [string]$Version
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$imagesDir = Join-Path $scriptDir 'season-images'
$manifestPath = Join-Path $scriptDir 'season-library.js'
$allowedExtensions = @('.png', '.jpg', '.jpeg', '.webp', '.gif')

function Escape-JsSingleQuoted {
  param([string]$Value)

  if ($null -eq $Value) { return '' }

  return $Value.Replace('\', '\\').Replace("'", "\'")
}

function Get-ManifestField {
  param([string]$FieldName)

  if (-not (Test-Path -LiteralPath $manifestPath)) { return '' }

  $text = Get-Content -LiteralPath $manifestPath -Raw
  $pattern = "{0}\s*:\s*'((?:\\'|[^'])*)'" -f [regex]::Escape($FieldName)
  $match = [regex]::Match($text, $pattern)
  if (-not $match.Success) { return '' }

  return $match.Groups[1].Value.Replace("\\'", "'").Replace('\\\\', '\')
}

function Prompt-OrDefault {
  param(
    [string]$Label,
    [string]$DefaultValue
  )

  $answer = Read-Host "$Label [$DefaultValue]"
  if ([string]::IsNullOrWhiteSpace($answer)) {
    return $DefaultValue
  }

  return $answer.Trim()
}

if (-not (Test-Path -LiteralPath $imagesDir)) {
  New-Item -ItemType Directory -Path $imagesDir | Out-Null
}

$seasonDefault = Get-ManifestField 'season'
if (-not $seasonDefault) {
  $seasonDefault = "season-$(Get-Date -Format 'yyyy-MM')"
}

$versionDefault = Get-Date -Format 'yyyy-MM-dd-HHmmss'

if (-not $Season) {
  $Season = Prompt-OrDefault 'Season label' $seasonDefault
}

if (-not $Version) {
  $Version = Prompt-OrDefault 'Version token' $versionDefault
}

$files = @(
  Get-ChildItem -LiteralPath $imagesDir -File |
    Where-Object { $allowedExtensions -contains $_.Extension.ToLowerInvariant() } |
    Sort-Object Name
)

if ($files.Count -eq 0) {
  Write-Host "No image files found in $imagesDir" -ForegroundColor Yellow
  Write-Host 'Add .png/.jpg/.jpeg/.webp/.gif files to season-images and run this script again.'
  exit 1
}

$manifestLines = @(
  '// Auto-generated by Update Season Library.ps1 from ./season-images/.',
  'window.PAINT_LAB_SEASON_LIBRARY = {',
  "  season: '$(Escape-JsSingleQuoted $Season)',",
  "  version: '$(Escape-JsSingleQuoted $Version)',",
  '  images: ['
)

for ($i = 0; $i -lt $files.Count; $i += 1) {
  $file = $files[$i]
  $name = Escape-JsSingleQuoted $file.Name
  $url = Escape-JsSingleQuoted ("season-images/{0}" -f ([Uri]::EscapeDataString($file.Name)))
  $suffix = if ($i -lt $files.Count - 1) { ',' } else { '' }
  $manifestLines += "    { name: '$name', url: '$url' }$suffix"
}

$manifestLines += @(
  '  ]',
  '};',
  ''
)

[System.IO.File]::WriteAllText(
  $manifestPath,
  ($manifestLines -join [Environment]::NewLine),
  [System.Text.UTF8Encoding]::new($false)
)

Write-Host ''
Write-Host "Updated season-library.js with $($files.Count) image(s)." -ForegroundColor Green
Write-Host "Season:  $Season"
Write-Host "Version: $Version"
Write-Host "Folder:  $imagesDir"
